DROP TABLE IF EXISTS ASENTAMIENTOS;
DROP TABLE IF EXISTS TIPO_ASENTAMIENTOS;
DROP TABLE IF EXISTS MUNICIPIOS;
DROP TABLE IF EXISTS ESTADOS;

CREATE TABLE ESTADOS (
 ID_ESTADO      INTEGER     NOT NULL AUTO_INCREMENT,
 CLAVE_ESTADO   VARCHAR(02) NOT NULL,
 ESTADO         VARCHAR(50) NOT NULL,
 PRIMARY KEY (ID_ESTADO)
);

CREATE TABLE MUNICIPIOS (
 ID_MUNICIPIO    INTEGER     NOT NULL  AUTO_INCREMENT,
 CLAVE_MUNICIPIO VARCHAR(03) NOT NULL,
 MUNICIPIO       VARCHAR(50) NOT NULL,
 ID_ESTADO       INTEGER,
 PRIMARY KEY (ID_MUNICIPIO),
 FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS (ID_ESTADO) ON DELETE CASCADE
);

CREATE TABLE TIPO_ASENTAMIENTOS (
 ID_TIPO_ASENTAMIENTO    INTEGER     NOT NULL AUTO_INCREMENT,
 CLAVE_TIPO_ASENTAMIENTO VARCHAR(02) NOT NULL,
 TIPO_ASENTAMIENTO       VARCHAR(50) NOT NULL,
 PRIMARY KEY (ID_TIPO_ASENTAMIENTO)
);

CREATE TABLE ASENTAMIENTOS (
 ID_ASENTAMIENTO      INTEGER     NOT NULL AUTO_INCREMENT,
 CODIGO_POSTAL        VARCHAR(05) NOT NULL,
 ASENTAMIENTO         VARCHAR(100) NOT NULL,
 CIUDAD               VARCHAR(50),
 ID_MUNICIPIO         INTEGER     NOT NULL,
 ID_TIPO_ASENTAMIENTO INTEGER     NOT NULL,
 PRIMARY KEY (ID_ASENTAMIENTO),
 FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIOS (ID_MUNICIPIO) ON DELETE CASCADE,
 FOREIGN KEY (ID_TIPO_ASENTAMIENTO) REFERENCES TIPO_ASENTAMIENTOS (ID_TIPO_ASENTAMIENTO) ON DELETE CASCADE
);
